### ISSUE TITLE
[Issue]: Helm Chart unavailable

### ISSUE THREAD

**Issue by LucaDev** [ROCm/k8s-device-plugin#49]
### Problem Description

The helm chart is not available anymore. Please add a note with the new helm repo url to the README and update the artifacthub links.
See: https://radeonopencompute.github.io/k8s-device-plugin/

I suppose its because of the switch from https://github.com/RadeonOpenCompute to https://github.com/ROCm

### Operating System

Helm

### CPU

-

### GPU

AMD Radeon VII

### ROCm Version

ROCm 6.0.0

### Steps to Reproduce

Try to pull the helm chart

**Comment by j0sh3rs** [comment]
@y2kenny-amd Was there any announcement made about the changing of the url? It looks like it was just silently updated without notice to your customers/consumers, which is really bad UX.

**Comment by y2kenny-amd** [comment]
> @y2kenny-amd Was there any announcement made about the changing of the url? It looks like it was just silently updated without notice to your customers/consumers, which is really bad UX.

It was an organization level thing outside of my control.  I raised alarm about the potential issues but the guys thought the redirect from old org would work (it didn't.)
